### ISSUE TITLE
Fonts branch merge checklist

### ISSUE THREAD

**Issue by wm4** [libass/libass#188]
So that we don't forget what there is to do.
- [x] The dwrite header in msys can't be used. Decide what to do about. Wait until it's fixed in msys? Use the internal copy? Use a more complete internal copy, instead of the minimal stripped down header that is there currently? (Also note that on MSVC the official dwrite header can't be used anyway, because it's not C compatible either.) (**Outcome: using our own stripped down dwrite header.**)
- [x] I still get broken text rendering on mpv's OSD. I have no idea why. (**Outcome: a commit to fix substitution handling has been pushed to the branch.**)
- [x] Add fallback handling to the CoreText backend. (**Outcome: implemented and tested**)
- [x] Calling ass_set_fonts() multiple times crashes with the DirectWrite backend. (This is sometimes needed when loading .ass files: they create an ASS_Track, which adds the font data to the ASS_Library - but it's picked up only when ass_set_fonts() is called. Maybe change it so that this happens transparently?) (**Outcome: the crash had a simple fix, and fixing the ASS_Track fonts is out of scope for now.**)
- [x] Does ass_set_fonts_dir() still work? Maybe we should reimplement them manually: scan the directory, add all font files as memory fonts. (**Outcome: it didn't. Reimplemented it in a lazy way.**)
- [x] Add explicit configure switches for DirectWrite and CoreText backends. (**Outcome: done.**)
- [x] Decide whether to add API for selecting font backend, and make the change. (**Outcome: actually, ``ass_set_fonts()`` allows selecting it.**)
- [x] Decide whether the font provider stuff should really be public API. (**Outcome: it shouldn't for now - we can always make it public later, while the other way around is harder.**)
- [x] The fontconfig with DirectWrite fallback does not really work. The problem is that the constructor return value is not checked. (**Outcome: fixed**)
- [x] DirectWrite lacks substitutions. Generic families should be mapped to sane defaults, at least. (**Outcome: basic substitutions implemented**)
- [x] match_fonts method for CoreText has some issues with substitutions and adding fonts multiple times, should be refactored.

**Comment by nille02** [comment]
Scanning for the fonts would be important. And please as a configured way. For my ffmpeg config i have a subdirectory fonts where all fonts placed. With the current way in dwrite i have to install all fonts in the system or register a custom set in dwrite. The last thing is a mess and not easy.

**Comment by grigorig** [comment]
Yes, I have already considered adding a simple directory-scanning backend.

**Comment by nille02** [comment]
will it be possible to configure it? e.g with a environment variable? let the application handle it can be a problem and for a config file there is a requirement for file system access.

**Comment by grigorig** [comment]
nille02, if you have special requirements, you can implement your own font provider.

**Comment by wiiaboo** [comment]
Afaict, he just wants to be able to use a custom fonts dir with ffmpeg as was possible with fontconfig and CUSTOMFONTDIR in fonts.conf.

No idea if you can do that with Dwrite too or override the default font provider for libass with some option if not?

**Comment by astiob** [comment]
That’s exactly what the `ass_set_fonts_dir` function does if I understand correctly. Perhaps FFmpeg should expose a command-line option to invoke this function.

**Comment by nille02** [comment]
i don't know, if they add this. as a other way. will it be possible, to set fontconfig later as the default fontrenderer, and not only as fallback?

**Comment by astiob** [comment]
You’d need an FFmpeg option for that too. Alternatively, if you compile your own libass, you should be able to disable DirectWrite by running `./configure --disable-directwrite`…

Hm, it seems we’re missing an `AC_ARG_ENABLE` in order to make this possible, and one for CoreText too. I’m not sure if the `AC_ARG_ENABLE` are required, but if they are, we should certainly add them.

**Comment by nille02** [comment]
Thanks, a option like that, is the only thing that i need in this case.

**Comment by wm4** [comment]
I added these two points to the TODO list.

**Comment by astiob** [comment]
Also, as much as I like pure C and consistency, I (currently) think we should go back to C++ so that our code works with the standard header shipped with MSVC. If not, then we should keep shipping our own `dwrite.h` until both MinGW and MSVC ship C-compatible headers. (And it would do no harm to file a bug or something with Microsoft asking them to fix this. I don’t have too much hope for this, but you never know.)

**Comment by wm4** [comment]
Well, it works now, and using 2 languages is better than 3. So I'd be for shipping our own header.

**Comment by wm4** [comment]
OK, let's assume that we all agree on keeping our fixed dwrite.h.

**Comment by wm4** [comment]
We changed homebrew-mpv to the fonts branch, so it'll get some testing at least.

**Comment by pigoz** [comment]
Looks like the fallback code is not implemented for CoreText, maybe an item should be added to the todo list.

**Comment by wm4** [comment]
Changed the OSX one to reflect this.

**Comment by wm4** [comment]
Added a new todo item.

Also:

> I still get broken text rendering on mpv's OSD. I have no idea why.

@grigorig had a patch against this, which worked, but needed cleanup.

**Comment by wm4** [comment]
2 more issues taken care of, including the one above...

**Comment by wm4** [comment]
Can anyone tell me what the fallback handling on CoreText is supposed to achieve?

**Comment by wm4** [comment]
OK, almost everything done, just the CoreText thing is missing.

**Comment by grigorig** [comment]
Great! Thank you for the nice work.

**Comment by wiiaboo** [comment]
Just confirming ass_set_fonts_dir works now: http://j.fsbn.eu/cL5w.txt

**Comment by Akemi** [comment]
@wm4 i could be mistaken but isn't it about the font issue i reported here https://github.com/libass/libass/issues/62#issuecomment-40698373

**Comment by grigorig** [comment]
So, we're done now. Merge time? :)

**Comment by wm4** [comment]
It got merged!

**Comment by pigoz** [comment]
:confetti_ball:
