### ISSUE TITLE
fontselect TODO

### ISSUE THREAD

**Issue by grigorig** [libass/libass#62]
This meta bug tracks current issues of the libass/fonts branch.

* [x] Handle duplicate fonts with match API
* [x] Improve fallback with a separate API
* [x] Handle platform-specific font aliases, if applicable
* [x] Choose sensible faces for generic families (sans-serif, serif, monospace, ...)
* [x] Don't sort the font list directly (unneeded memcpy)
* [x] Check compatibility with VSFilter in unusual cases
* [ ] Test coretext backend (bugs and compatibility)
* [ ] Think about priority of embedded fonts vs other/default providers

**Comment by Andrea3000** [comment]
I found what causes the issue that Akemi has reported.

The font that doesn't display correctly is named "Impress BT" and is attached to the movie file.
Because of the space in the font name, the glyphs can't be read.

I've extracted the font and the subtitle file from the movie, renamed the font to ImpressBT (without the space), modified the ass subtitle accordingly and repacked everything together.
It now works just fine with libass-ct.

You can find the file here: https://dl.dropboxusercontent.com/u/11879013/font-test-mod.mkv

However, I'm not familiar with the libass code to fix the code myself.

**Comment by grigorig** [comment]
Updated the first post. fontselect now has fontconfig, directwrite and coretext backends. The first two are known to work well, while coretext has various issues.

There are some smaller open questions as well.
- Do we need full Unicode-aware case-insensitive string comparisons (aka string collation)?
- Is the fallback selection interface sensible?
